import type { LessonVisualMap } from "./types";

export const grade8Visuals: LessonVisualMap = {
  "g8-triangle-basics": "triangle",
  "g8-triangle-sides": "triangle",
  "g8-triangle-angles-polygons": "triangle",
  "g8-congruence-rules": "congruence",
  "g8-right-triangle-proof": "congruence",
  "g8-angle-bisector": "geometry-basics",
  "g8-axis-symmetry-basics": "symmetry",
  "g8-perpendicular-bisector": "symmetry",
  "g8-isosceles-equilateral": "triangle",
  "g8-powers-polynomial-multiplication": "algebra-tiles",
  "g8-multiplication-formulas": "algebra-tiles",
  "g8-factoring": "algebra-tiles",
  "g8-rational-expression-basics": "operation",
  "g8-rational-expression-operations": "operation",
  "g8-rational-equations": "balance",
  "g8-radical-meaning-simplify": "roots",
  "g8-radical-operations": "roots",
  "g8-pythagorean-theorem": "right-triangle",
  "g8-pythagorean-converse-application": "right-triangle",
  "g8-parallelogram": "quadrilateral",
  "g8-rectangle": "quadrilateral",
  "g8-rhombus": "quadrilateral",
  "g8-square": "quadrilateral",
  "g8-midsegment": "triangle",
  "g8-function-coordinate": "coordinate",
  "g8-direct-linear-functions": "linear-graph",
  "g8-linear-function-applications": "linear-graph",
  "g8-mean-weighted-mean": "data-chart",
  "g8-median-mode-variance": "data-chart",
  "g8-sampling-probability": "probability",
};
